# Generated by Django 4.1.7 on 2023-02-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animestorage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
    ]
