# Generated by Django 4.1.7 on 2023-02-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animestorage', '0002_genre_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
