# Generated by Django 4.1.7 on 2023-02-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animestorage', '0004_alter_genre_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='agerating',
            name='date_added',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата добавления в базу'),
        ),
        migrations.AddField(
            model_name='anime',
            name='date_added',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата добавления в базу'),
        ),
        migrations.AddField(
            model_name='anime',
            name='release_year',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Год выпуска'),
        ),
        migrations.AddField(
            model_name='animetype',
            name='date_added',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата добавления в базу'),
        ),
        migrations.AddField(
            model_name='genre',
            name='date_added',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата добавления в базу'),
        ),
        migrations.AddField(
            model_name='status',
            name='date_added',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата добавления в базу'),
        ),
        migrations.AddField(
            model_name='studio',
            name='date_added',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата добавления в базу'),
        ),
    ]
